[project]
name = "theory-of-complex-systems"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.1",
    "notebook>=7.4.0",
    "pyqt5>=5.15.11",
    "scikit-learn>=1.6.1",
]
